markdown: rdiscount

papertitle: Scalable Component Abstractions
paperurl: http://lampwww.epfl.ch/~odersky/papers/ScalableComponent.pdf
nextmeetingdate: "January 16, 2014"
nextmeetingtime: "11:30-13h"
nextmeetingloc: "INM331 (LAMP/LARA meeting room)"
